### ISSUE TITLE
the requirements of this project

### ISSUE THREAD

**Issue by gszfwsb** [eg-10/Fast-Neural-Style-Transfer#1]
I cannot run this project in my ubuntu machine. Once I uploaded the image and then click the style image, the page roll up and nothing happens. I had my Pytorch and CUDA installed.  And it seems nothing wrong with the HTTP requests. So could you please show us your requirements?

**Comment by eg-10** [comment]
Check if you've installed Pillow. The requirements are just PyTorch, Django and Pillow.
